Repository GSG-G7/handyman, pull requests merged in 2019-09, with the labels that each got.

#2 create readme
  README.md
Labels: need review

#21 Fix typos
  README.md
Labels: done

#45 File Structure BackEnd
  server/app.js
  server/controllers/index.js
  server/controllers/middleware/.gitkeep
  server/controllers/routes/.gitkeep
  server/controllers/utils/.gitkeep
  server/db/config/build.js
  server/db/config/build.sql
  server/db/config/connection.js
  server/db/config/fakeData.sql
  server/db/queries/.gitkeep
  server/index.js
  server/template/.gitkeep
  server/tests/queries/.gitkeep
  server/tests/routes/.gitkeep
  server/tests/utils/.gitkeep
Labels: Awaiting Review

#48 file structure (client file)
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/assets/.gitkeep
  client/src/components/app/App.css
  client/src/components/app/App.js
  client/src/components/auth/.gitkeep
  client/src/components/pages/.gitkeep
  client/src/components/utils/.gitkeep
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  client/src/utils/.gitkeep
Labels: Awaiting Review

#49 Initialize the app
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/index.js
  server/tests/index.js
  server/tests/queries/.gitkeep
  server/tests/queries/index.js
  server/tests/routes/.gitkeep
  server/tests/routes/index.js
  server/tests/utils/.gitkeep
  server/tests/utils/index.js
Labels: Awaiting Review

#53 Initialize the app
  package.json
Labels: Awaiting Review

#50 create the database shcema
  server/db/config/build.sql
Labels: Awaiting Review

#54 travis database setup
  .travis.yml
Labels: Awaiting Review

#62 unlock cookie middleware
  server/controllers/middleware/.gitkeep
  server/controllers/middleware/unlockCookie.js
Labels: need review

#64 Logout
  .gitignore
  server/controllers/index.js
  server/controllers/routes/getLogout.js
Labels: Awaiting Review

#57 GetJobs (Query, Test, Endpoint)
  server/controllers/index.js
  server/controllers/middleware/unlockCookie.js
  server/controllers/routes/.gitkeep
  server/controllers/routes/getJobs.js
  server/controllers/routes/index.js
  server/db/config/fakeData.sql
  server/db/queries/.gitkeep
  server/db/queries/getJobs.js
  server/tests/queries/getJob.js
  server/tests/queries/index.js
  server/tests/routes/getJob.js
  server/tests/routes/index.js
Labels: need review

#65 GetProfile (Query, Test, Endpoint)
  server/controllers/index.js
  server/controllers/routes/getProfile.js
  server/controllers/routes/index.js
  server/db/queries/getProfile.js
  server/tests/queries/getProfile.js
  server/tests/queries/index.js
  server/tests/routes/getProfile.js
  server/tests/routes/index.js
Labels: Done

#67 get services
  server/controllers/index.js
  server/controllers/routes/getServices.js
  server/controllers/routes/index.js
  server/db/queries/getServices.js
  server/tests/queries/getServices.js
  server/tests/queries/index.js
  server/tests/routes/getServices.js
  server/tests/routes/index.js
Labels: Done

#60 Add new job
  server/controllers/ValidationSchemas/newJobSchema.js
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/postJob.js
  server/db/queries/postJob.js
  server/tests/queries/index.js
  server/tests/queries/postJob.js
  server/tests/routes/index.js
  server/tests/routes/postJob.js
Labels: Awaiting Review

#70 Eslint Configuration & install packages | Front
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/components/App/index.js
  client/src/index.js
  client/src/serviceWorker.js
Labels: Done

#59 signup post route
  server/app.js
  server/controllers/index.js
  server/controllers/middleware/unlockCookie.js
  server/controllers/routes/index.js
  server/controllers/routes/postJob.js
  server/controllers/routes/signup.js
  server/controllers/utils/cookie.js
  server/controllers/utils/password.js
  server/controllers/validationSchemas/clientSchema.js
  server/controllers/validationSchemas/handymanSchema.js
  server/controllers/validationSchemas/newJobSchema.js
  server/db/queries/addHandyman.js
  server/db/queries/addUser.js
  server/tests/queries/index.js
  server/tests/queries/signupQuery.js
  server/tests/routes/index.js
  server/tests/routes/signup.js
  server/tests/utils/index.js
Labels: Done

#66 login
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/login.js
  server/controllers/utils/password.js
  server/controllers/validationSchemas/loginSchema.js
  server/db/config/fakeData.sql
  server/db/queries/getUserByEmail.js
  server/tests/queries/getUserByEmail.js
  server/tests/queries/index.js
  server/tests/routes/index.js
  server/tests/routes/login.js
Labels: Done

#72 Create Button Component
  client/package.json
  client/src/components/common/Button/index.js
  client/src/components/common/Button/style.css
Labels: Awaiting Review

#71 Footer components
  client/public/index.html
  client/src/components/App/style.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
Labels: Done

#76 Edit getjob query
  server/db/queries/getJobs.js
Labels: Done

#74 labeld input with style
  client/src/components/common/LabeledInput/index.js
  client/src/components/common/LabeledInput/style.css
Labels: Awaiting Review

#73 ServiceCard Component
  client/.eslintrc.js
  client/src/components/common/serviceCard/index.js
  client/src/components/common/serviceCard/style.css
Labels: Done

#79 Textarea components
  client/src/components/common/Textarea/index.js
  client/src/components/common/Textarea/style.css
Labels: Done

#78 header component
  client/public/index.html
  client/src/components/common/Header/index.js
  client/src/components/common/Header/style.css
Labels: Done

#81 remove unnecessary require and enhance the validation schema
  server/controllers/middleware/unlockCookie.js
  server/controllers/routes/signup.js
  server/controllers/validationSchemas/handymanSchema.js
  server/controllers/validationSchemas/userSchema.js
Labels: Backend, Done, enhancement

#80 JobCard Component
  client/src/assets/handyman.png
  client/src/components/common/JobCard/index.js
  client/src/components/common/JobCard/style.css
Labels: Done

#87 star component
  client/src/components/common/Star/index.js
  client/src/components/common/Star/style.css
Labels: Done

#77 Slider card Component
  client/src/components/common/sliderCard/index.js
  client/src/components/common/sliderCard/style.css
Labels: Awaiting Review

#83 SideDrawer Components
  client/src/components/App/style.css
  client/src/components/common/DrawerToggleButton/index.js
  client/src/components/common/DrawerToggleButton/style.css
  client/src/components/common/SideDrawer/index.js
  client/src/components/common/SideDrawer/style.css
Labels: Done

#82 Profile Card Component
  client/src/assets/.gitkeep
  client/src/components/common/ProfileCard/index.js
  client/src/components/common/ProfileCard/style.css
Labels: Done

#88 edit style JobCard Component and add the Rate
  client/src/components/common/JobCard/index.js
  client/src/components/common/JobCard/style.css
Labels: Done

#85 Card Component
  client/src/components/common/HandymanCard/index.js
  client/src/components/common/HandymanCard/style.css
  client/src/components/common/Star/style.css
Labels: Awaiting Review

#91 change the onClick function name in props
  client/src/components/common/Button/index.js
Labels: Done

#92 Select role Component
  client/src/components/common/selectOption/index.js
  client/src/components/common/selectOption/style.css
Labels: Awaiting Review

#94 Search input component
  client/src/components/common/SearchInput/index.js
  client/src/components/common/SearchInput/style.css
  client/src/components/common/serviceCard/style.css
Labels: Done
